package LLD.Problems.TaskManagementSystem.models;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import LLD.Problems.TaskManagementSystem.enums.PriorityLevel;
import LLD.Problems.TaskManagementSystem.enums.TaskStatus;

public class TaskManagementSystem {
  private Map<String, User> users;
  private Map<String, Task> tasks;
  private static TaskManagementSystem INSTANCE;

  private TaskManagementSystem() {
    users = new HashMap<>();
    tasks = new HashMap<>();
  }

  public synchronized static TaskManagementSystem getInstance() {
    if(INSTANCE == null) {
      INSTANCE = new TaskManagementSystem();
    }
    return INSTANCE;
  }

  public User addUser(String id, String name) {
    // ideally id as uuid should be used & generated by system and we return the id not the whole object
    User user = new User(id, name);
    users.put(id, user);
    return user;
  }

  public void removeUser(String id) {
    if(users.containsKey(id)) users.remove(id);    
  }

  public Task createTask(String taskId, String title, String description, String creatorUserId, PriorityLevel priority, LocalDateTime dueDate) {
    Task task = new Task(taskId, title, description, users.get(creatorUserId), priority, dueDate);
    tasks.put(taskId, task);
    return task;
  }

  public void deleteTask(String id) {
    if(tasks.containsKey(id)) tasks.remove(id);
  }

  public Task getTaskById(String id) {
    if(tasks.containsKey(id)) return tasks.get(id);
    return null;
  }

  public void startTaskById(String id) {
    Task task = tasks.get(id);
    if(task == null) {
      System.out.println("Invalid ID.");
      return;
    }
    if(task.getTaskStatus() != TaskStatus.TODO) {
      System.out.println("Task is either already in progress or completed.");
      return;
    }
    task.setStatus(TaskStatus.IN_PROGRESS);
  }

  public void markTaskAsCompleted(String id) {
    Task task = tasks.get(id);
    if(task == null) {
      System.out.println("Invalid ID.");
      return;
    }
    task.setStatus(TaskStatus.COMPLETED);
  }

  public void reOpenTask(String id) {
    Task task = tasks.get(id);
    if(task == null) {
      System.out.println("Invalid ID.");
      return;
    }
    if(task.getTaskStatus() != TaskStatus.COMPLETED) {
      System.out.println("Task already opened.");
      return;
    }
    task.setStatus(TaskStatus.TODO); 
  }

  public List<Task> filterBasedOnPriority(PriorityLevel level) {
    List<Task> filteredTasks = new ArrayList<>();
    for(Map.Entry<String, Task> task: tasks.entrySet()) {
      if(task.getValue().getPriorityLevel() == level) {
        filteredTasks.add(task.getValue());
      }
    }
    return filteredTasks;
  }
}
